/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabsIndexRouteImport } from './routes/labs.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as VerifySerialRouteImport } from './routes/verify.$serial'
import { Route as LabsSlugRouteImport } from './routes/labs.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedLearnBatchIdRouteImport } from './routes/_authenticated/learn.$batchId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSiteRouteImport } from './routes/_authenticated/admin.site'
import { Route as AuthenticatedAdminShopRouteImport } from './routes/_authenticated/admin.shop'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated/admin.courses.index'
import { Route as AuthenticatedReportsBatchIdUserIdRouteImport } from './routes/_authenticated/reports.$batchId.$userId'
import { Route as AuthenticatedLearnBatchIdAssignmentsRouteImport } from './routes/_authenticated/learn.$batchId.assignments'
import { Route as AuthenticatedLearnBatchIdQuizQuizIdRouteImport } from './routes/_authenticated/learn.$batchId.quiz.$quizId'
import { Route as AuthenticatedAdminCoursesSlugBatchesRouteImport } from './routes/_authenticated/admin.courses.$slug.batches'
import { Route as AuthenticatedAdminBatchesIdStudentsRouteImport } from './routes/_authenticated/admin.batches.$id.students'
import { Route as AuthenticatedAdminBatchesIdReportsRouteImport } from './routes/_authenticated/admin.batches.$id.reports'
import { Route as AuthenticatedAdminBatchesIdQuizzesRouteImport } from './routes/_authenticated/admin.batches.$id.quizzes'
import { Route as AuthenticatedAdminBatchesIdLecturesRouteImport } from './routes/_authenticated/admin.batches.$id.lectures'
import { Route as AuthenticatedAdminBatchesIdCouponsRouteImport } from './routes/_authenticated/admin.batches.$id.coupons'
import { Route as AuthenticatedAdminBatchesIdAttendanceRouteImport } from './routes/_authenticated/admin.batches.$id.attendance'
import { Route as AuthenticatedAdminBatchesIdAssignmentsRouteImport } from './routes/_authenticated/admin.batches.$id.assignments'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const VerifySerialRoute = VerifySerialRouteImport.update({
  id: '/verify/$serial',
  path: '/verify/$serial',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsSlugRoute = LabsSlugRouteImport.update({
  id: '/labs/$slug',
  path: '/labs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnBatchIdRoute =
  AuthenticatedLearnBatchIdRouteImport.update({
    id: '/learn/$batchId',
    path: '/learn/$batchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSiteRoute = AuthenticatedAdminSiteRouteImport.update({
  id: '/admin/site',
  path: '/admin/site',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminShopRoute = AuthenticatedAdminShopRouteImport.update({
  id: '/admin/shop',
  path: '/admin/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/admin/coupons',
    path: '/admin/coupons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/admin/contact',
    path: '/admin/contact',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/admin/courses/',
    path: '/admin/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsBatchIdUserIdRoute =
  AuthenticatedReportsBatchIdUserIdRouteImport.update({
    id: '/reports/$batchId/$userId',
    path: '/reports/$batchId/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnBatchIdAssignmentsRoute =
  AuthenticatedLearnBatchIdAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedLearnBatchIdRoute,
  } as any)
const AuthenticatedLearnBatchIdQuizQuizIdRoute =
  AuthenticatedLearnBatchIdQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => AuthenticatedLearnBatchIdRoute,
  } as any)
const AuthenticatedAdminCoursesSlugBatchesRoute =
  AuthenticatedAdminCoursesSlugBatchesRouteImport.update({
    id: '/admin/courses/$slug/batches',
    path: '/admin/courses/$slug/batches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBatchesIdStudentsRoute =
  AuthenticatedAdminBatchesIdStudentsRouteImport.update({
    id: '/admin/batches/$id/students',
    path: '/admin/batches/$id/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBatchesIdReportsRoute =
  AuthenticatedAdminBatchesIdReportsRouteImport.update({
    id: '/admin/batches/$id/reports',
    path: '/admin/batches/$id/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBatchesIdQuizzesRoute =
  AuthenticatedAdminBatchesIdQuizzesRouteImport.update({
    id: '/admin/batches/$id/quizzes',
    path: '/admin/batches/$id/quizzes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBatchesIdLecturesRoute =
  AuthenticatedAdminBatchesIdLecturesRouteImport.update({
    id: '/admin/batches/$id/lectures',
    path: '/admin/batches/$id/lectures',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBatchesIdCouponsRoute =
  AuthenticatedAdminBatchesIdCouponsRouteImport.update({
    id: '/admin/batches/$id/coupons',
    path: '/admin/batches/$id/coupons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBatchesIdAttendanceRoute =
  AuthenticatedAdminBatchesIdAttendanceRouteImport.update({
    id: '/admin/batches/$id/attendance',
    path: '/admin/batches/$id/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBatchesIdAssignmentsRoute =
  AuthenticatedAdminBatchesIdAssignmentsRouteImport.update({
    id: '/admin/batches/$id/assignments',
    path: '/admin/batches/$id/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/shop': typeof ShopRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/labs/$slug': typeof LabsSlugRoute
  '/verify/$serial': typeof VerifySerialRoute
  '/courses/': typeof CoursesIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/learn/$batchId': typeof AuthenticatedLearnBatchIdRouteWithChildren
  '/learn/$batchId/assignments': typeof AuthenticatedLearnBatchIdAssignmentsRoute
  '/reports/$batchId/$userId': typeof AuthenticatedReportsBatchIdUserIdRoute
  '/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/batches/$id/assignments': typeof AuthenticatedAdminBatchesIdAssignmentsRoute
  '/admin/batches/$id/attendance': typeof AuthenticatedAdminBatchesIdAttendanceRoute
  '/admin/batches/$id/coupons': typeof AuthenticatedAdminBatchesIdCouponsRoute
  '/admin/batches/$id/lectures': typeof AuthenticatedAdminBatchesIdLecturesRoute
  '/admin/batches/$id/quizzes': typeof AuthenticatedAdminBatchesIdQuizzesRoute
  '/admin/batches/$id/reports': typeof AuthenticatedAdminBatchesIdReportsRoute
  '/admin/batches/$id/students': typeof AuthenticatedAdminBatchesIdStudentsRoute
  '/admin/courses/$slug/batches': typeof AuthenticatedAdminCoursesSlugBatchesRoute
  '/learn/$batchId/quiz/$quizId': typeof AuthenticatedLearnBatchIdQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/shop': typeof ShopRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/labs/$slug': typeof LabsSlugRoute
  '/verify/$serial': typeof VerifySerialRoute
  '/courses': typeof CoursesIndexRoute
  '/labs': typeof LabsIndexRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/learn/$batchId': typeof AuthenticatedLearnBatchIdRouteWithChildren
  '/learn/$batchId/assignments': typeof AuthenticatedLearnBatchIdAssignmentsRoute
  '/reports/$batchId/$userId': typeof AuthenticatedReportsBatchIdUserIdRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/batches/$id/assignments': typeof AuthenticatedAdminBatchesIdAssignmentsRoute
  '/admin/batches/$id/attendance': typeof AuthenticatedAdminBatchesIdAttendanceRoute
  '/admin/batches/$id/coupons': typeof AuthenticatedAdminBatchesIdCouponsRoute
  '/admin/batches/$id/lectures': typeof AuthenticatedAdminBatchesIdLecturesRoute
  '/admin/batches/$id/quizzes': typeof AuthenticatedAdminBatchesIdQuizzesRoute
  '/admin/batches/$id/reports': typeof AuthenticatedAdminBatchesIdReportsRoute
  '/admin/batches/$id/students': typeof AuthenticatedAdminBatchesIdStudentsRoute
  '/admin/courses/$slug/batches': typeof AuthenticatedAdminCoursesSlugBatchesRoute
  '/learn/$batchId/quiz/$quizId': typeof AuthenticatedLearnBatchIdQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/shop': typeof ShopRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/labs/$slug': typeof LabsSlugRoute
  '/verify/$serial': typeof VerifySerialRoute
  '/courses/': typeof CoursesIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/shop': typeof AuthenticatedAdminShopRoute
  '/_authenticated/admin/site': typeof AuthenticatedAdminSiteRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/learn/$batchId': typeof AuthenticatedLearnBatchIdRouteWithChildren
  '/_authenticated/learn/$batchId/assignments': typeof AuthenticatedLearnBatchIdAssignmentsRoute
  '/_authenticated/reports/$batchId/$userId': typeof AuthenticatedReportsBatchIdUserIdRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/admin/batches/$id/assignments': typeof AuthenticatedAdminBatchesIdAssignmentsRoute
  '/_authenticated/admin/batches/$id/attendance': typeof AuthenticatedAdminBatchesIdAttendanceRoute
  '/_authenticated/admin/batches/$id/coupons': typeof AuthenticatedAdminBatchesIdCouponsRoute
  '/_authenticated/admin/batches/$id/lectures': typeof AuthenticatedAdminBatchesIdLecturesRoute
  '/_authenticated/admin/batches/$id/quizzes': typeof AuthenticatedAdminBatchesIdQuizzesRoute
  '/_authenticated/admin/batches/$id/reports': typeof AuthenticatedAdminBatchesIdReportsRoute
  '/_authenticated/admin/batches/$id/students': typeof AuthenticatedAdminBatchesIdStudentsRoute
  '/_authenticated/admin/courses/$slug/batches': typeof AuthenticatedAdminCoursesSlugBatchesRoute
  '/_authenticated/learn/$batchId/quiz/$quizId': typeof AuthenticatedLearnBatchIdQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/faculty'
    | '/faq'
    | '/feedback'
    | '/shop'
    | '/analytics'
    | '/certificates'
    | '/courses/$slug'
    | '/labs/$slug'
    | '/verify/$serial'
    | '/courses/'
    | '/labs/'
    | '/admin/contact'
    | '/admin/coupons'
    | '/admin/shop'
    | '/admin/site'
    | '/admin/users'
    | '/learn/$batchId'
    | '/learn/$batchId/assignments'
    | '/reports/$batchId/$userId'
    | '/admin/courses/'
    | '/admin/batches/$id/assignments'
    | '/admin/batches/$id/attendance'
    | '/admin/batches/$id/coupons'
    | '/admin/batches/$id/lectures'
    | '/admin/batches/$id/quizzes'
    | '/admin/batches/$id/reports'
    | '/admin/batches/$id/students'
    | '/admin/courses/$slug/batches'
    | '/learn/$batchId/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/faculty'
    | '/faq'
    | '/feedback'
    | '/shop'
    | '/analytics'
    | '/certificates'
    | '/courses/$slug'
    | '/labs/$slug'
    | '/verify/$serial'
    | '/courses'
    | '/labs'
    | '/admin/contact'
    | '/admin/coupons'
    | '/admin/shop'
    | '/admin/site'
    | '/admin/users'
    | '/learn/$batchId'
    | '/learn/$batchId/assignments'
    | '/reports/$batchId/$userId'
    | '/admin/courses'
    | '/admin/batches/$id/assignments'
    | '/admin/batches/$id/attendance'
    | '/admin/batches/$id/coupons'
    | '/admin/batches/$id/lectures'
    | '/admin/batches/$id/quizzes'
    | '/admin/batches/$id/reports'
    | '/admin/batches/$id/students'
    | '/admin/courses/$slug/batches'
    | '/learn/$batchId/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/faculty'
    | '/faq'
    | '/feedback'
    | '/shop'
    | '/_authenticated/analytics'
    | '/_authenticated/certificates'
    | '/courses/$slug'
    | '/labs/$slug'
    | '/verify/$serial'
    | '/courses/'
    | '/labs/'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/shop'
    | '/_authenticated/admin/site'
    | '/_authenticated/admin/users'
    | '/_authenticated/learn/$batchId'
    | '/_authenticated/learn/$batchId/assignments'
    | '/_authenticated/reports/$batchId/$userId'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/batches/$id/assignments'
    | '/_authenticated/admin/batches/$id/attendance'
    | '/_authenticated/admin/batches/$id/coupons'
    | '/_authenticated/admin/batches/$id/lectures'
    | '/_authenticated/admin/batches/$id/quizzes'
    | '/_authenticated/admin/batches/$id/reports'
    | '/_authenticated/admin/batches/$id/students'
    | '/_authenticated/admin/courses/$slug/batches'
    | '/_authenticated/learn/$batchId/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FacultyRoute: typeof FacultyRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  ShopRoute: typeof ShopRoute
  LabsSlugRoute: typeof LabsSlugRoute
  VerifySerialRoute: typeof VerifySerialRoute
  LabsIndexRoute: typeof LabsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/verify/$serial': {
      id: '/verify/$serial'
      path: '/verify/$serial'
      fullPath: '/verify/$serial'
      preLoaderRoute: typeof VerifySerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$slug': {
      id: '/labs/$slug'
      path: '/labs/$slug'
      fullPath: '/labs/$slug'
      preLoaderRoute: typeof LabsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$batchId': {
      id: '/_authenticated/learn/$batchId'
      path: '/learn/$batchId'
      fullPath: '/learn/$batchId'
      preLoaderRoute: typeof AuthenticatedLearnBatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/site': {
      id: '/_authenticated/admin/site'
      path: '/admin/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AuthenticatedAdminSiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/shop': {
      id: '/_authenticated/admin/shop'
      path: '/admin/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AuthenticatedAdminShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$batchId/$userId': {
      id: '/_authenticated/reports/$batchId/$userId'
      path: '/reports/$batchId/$userId'
      fullPath: '/reports/$batchId/$userId'
      preLoaderRoute: typeof AuthenticatedReportsBatchIdUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$batchId/assignments': {
      id: '/_authenticated/learn/$batchId/assignments'
      path: '/assignments'
      fullPath: '/learn/$batchId/assignments'
      preLoaderRoute: typeof AuthenticatedLearnBatchIdAssignmentsRouteImport
      parentRoute: typeof AuthenticatedLearnBatchIdRoute
    }
    '/_authenticated/learn/$batchId/quiz/$quizId': {
      id: '/_authenticated/learn/$batchId/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/learn/$batchId/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedLearnBatchIdQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedLearnBatchIdRoute
    }
    '/_authenticated/admin/courses/$slug/batches': {
      id: '/_authenticated/admin/courses/$slug/batches'
      path: '/admin/courses/$slug/batches'
      fullPath: '/admin/courses/$slug/batches'
      preLoaderRoute: typeof AuthenticatedAdminCoursesSlugBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/batches/$id/students': {
      id: '/_authenticated/admin/batches/$id/students'
      path: '/admin/batches/$id/students'
      fullPath: '/admin/batches/$id/students'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIdStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/batches/$id/reports': {
      id: '/_authenticated/admin/batches/$id/reports'
      path: '/admin/batches/$id/reports'
      fullPath: '/admin/batches/$id/reports'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIdReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/batches/$id/quizzes': {
      id: '/_authenticated/admin/batches/$id/quizzes'
      path: '/admin/batches/$id/quizzes'
      fullPath: '/admin/batches/$id/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIdQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/batches/$id/lectures': {
      id: '/_authenticated/admin/batches/$id/lectures'
      path: '/admin/batches/$id/lectures'
      fullPath: '/admin/batches/$id/lectures'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIdLecturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/batches/$id/coupons': {
      id: '/_authenticated/admin/batches/$id/coupons'
      path: '/admin/batches/$id/coupons'
      fullPath: '/admin/batches/$id/coupons'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIdCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/batches/$id/attendance': {
      id: '/_authenticated/admin/batches/$id/attendance'
      path: '/admin/batches/$id/attendance'
      fullPath: '/admin/batches/$id/attendance'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIdAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/batches/$id/assignments': {
      id: '/_authenticated/admin/batches/$id/assignments'
      path: '/admin/batches/$id/assignments'
      fullPath: '/admin/batches/$id/assignments'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIdAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedLearnBatchIdRouteChildren {
  AuthenticatedLearnBatchIdAssignmentsRoute: typeof AuthenticatedLearnBatchIdAssignmentsRoute
  AuthenticatedLearnBatchIdQuizQuizIdRoute: typeof AuthenticatedLearnBatchIdQuizQuizIdRoute
}

const AuthenticatedLearnBatchIdRouteChildren: AuthenticatedLearnBatchIdRouteChildren =
  {
    AuthenticatedLearnBatchIdAssignmentsRoute:
      AuthenticatedLearnBatchIdAssignmentsRoute,
    AuthenticatedLearnBatchIdQuizQuizIdRoute:
      AuthenticatedLearnBatchIdQuizQuizIdRoute,
  }

const AuthenticatedLearnBatchIdRouteWithChildren =
  AuthenticatedLearnBatchIdRoute._addFileChildren(
    AuthenticatedLearnBatchIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminShopRoute: typeof AuthenticatedAdminShopRoute
  AuthenticatedAdminSiteRoute: typeof AuthenticatedAdminSiteRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedLearnBatchIdRoute: typeof AuthenticatedLearnBatchIdRouteWithChildren
  AuthenticatedReportsBatchIdUserIdRoute: typeof AuthenticatedReportsBatchIdUserIdRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
  AuthenticatedAdminBatchesIdAssignmentsRoute: typeof AuthenticatedAdminBatchesIdAssignmentsRoute
  AuthenticatedAdminBatchesIdAttendanceRoute: typeof AuthenticatedAdminBatchesIdAttendanceRoute
  AuthenticatedAdminBatchesIdCouponsRoute: typeof AuthenticatedAdminBatchesIdCouponsRoute
  AuthenticatedAdminBatchesIdLecturesRoute: typeof AuthenticatedAdminBatchesIdLecturesRoute
  AuthenticatedAdminBatchesIdQuizzesRoute: typeof AuthenticatedAdminBatchesIdQuizzesRoute
  AuthenticatedAdminBatchesIdReportsRoute: typeof AuthenticatedAdminBatchesIdReportsRoute
  AuthenticatedAdminBatchesIdStudentsRoute: typeof AuthenticatedAdminBatchesIdStudentsRoute
  AuthenticatedAdminCoursesSlugBatchesRoute: typeof AuthenticatedAdminCoursesSlugBatchesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminShopRoute: AuthenticatedAdminShopRoute,
  AuthenticatedAdminSiteRoute: AuthenticatedAdminSiteRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedLearnBatchIdRoute: AuthenticatedLearnBatchIdRouteWithChildren,
  AuthenticatedReportsBatchIdUserIdRoute:
    AuthenticatedReportsBatchIdUserIdRoute,
  AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
  AuthenticatedAdminBatchesIdAssignmentsRoute:
    AuthenticatedAdminBatchesIdAssignmentsRoute,
  AuthenticatedAdminBatchesIdAttendanceRoute:
    AuthenticatedAdminBatchesIdAttendanceRoute,
  AuthenticatedAdminBatchesIdCouponsRoute:
    AuthenticatedAdminBatchesIdCouponsRoute,
  AuthenticatedAdminBatchesIdLecturesRoute:
    AuthenticatedAdminBatchesIdLecturesRoute,
  AuthenticatedAdminBatchesIdQuizzesRoute:
    AuthenticatedAdminBatchesIdQuizzesRoute,
  AuthenticatedAdminBatchesIdReportsRoute:
    AuthenticatedAdminBatchesIdReportsRoute,
  AuthenticatedAdminBatchesIdStudentsRoute:
    AuthenticatedAdminBatchesIdStudentsRoute,
  AuthenticatedAdminCoursesSlugBatchesRoute:
    AuthenticatedAdminCoursesSlugBatchesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FacultyRoute: FacultyRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  ShopRoute: ShopRoute,
  LabsSlugRoute: LabsSlugRoute,
  VerifySerialRoute: VerifySerialRoute,
  LabsIndexRoute: LabsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
